// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByr-HxprTxTcjehVgRf19_tpYIPrtL2YM',
    appId: '1:939119036503:web:b1014c7000b29664b8bb12',
    messagingSenderId: '939119036503',
    projectId: 'kit721-7ef30',
    authDomain: 'kit721-7ef30.firebaseapp.com',
    storageBucket: 'kit721-7ef30.appspot.com',
    measurementId: 'G-HKH5JGM14W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfRTUPJcoth_MFAPuf64s6dei6IbGzY-s',
    appId: '1:939119036503:android:46a147e5e5132ddeb8bb12',
    messagingSenderId: '939119036503',
    projectId: 'kit721-7ef30',
    storageBucket: 'kit721-7ef30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlI9008KIhOWfh2zTKHTzjPBJpxu5PVd8',
    appId: '1:939119036503:ios:bc5b4885c625567bb8bb12',
    messagingSenderId: '939119036503',
    projectId: 'kit721-7ef30',
    storageBucket: 'kit721-7ef30.appspot.com',
    iosClientId: '939119036503-457iqom9s2mo3ughb2ca536jlu7k5l4d.apps.googleusercontent.com',
    iosBundleId: 'au.utas.edu.apandey3.kit721.babyCare',
  );
}
